import type { TechStack, Documentation, DiagramSpec, ThesisAnalysis } from "./openrouter";

export interface ProjectExportData {
  name: string;
  sourceType: string;
  sourceRef: string;
  techStack: TechStack;
  documentation: Documentation;
  diagrams: DiagramSpec[];
  thesisAnalysis?: ThesisAnalysis | null;
}

function hasDiagrams(data: ProjectExportData): boolean {
  return data.diagrams && data.diagrams.length > 0;
}

function hasApiEndpoints(data: ProjectExportData): boolean {
  return data.documentation.apiEndpoints.length > 0;
}

function hasDataModels(data: ProjectExportData): boolean {
  return data.documentation.dataModels.length > 0;
}

export function buildMarkdown(data: ProjectExportData): string {
  const { name, sourceRef, techStack, documentation, diagrams, thesisAnalysis } = data;
  const lines: string[] = [];

  const showDiagrams = hasDiagrams(data);
  const showApi = hasApiEndpoints(data);
  const showModels = hasDataModels(data);
  const showThesis = !!thesisAnalysis;

  // Compute offsets
  let s = 0;
  const secAbstract = ++s;        // 1
  const secTech = ++s;            // 2
  const secArch = ++s;            // 3
  const secDiagrams = showDiagrams ? ++s : s; // 4 (conditional)
  const secFolders = ++s;         // 5
  const secModules = ++s;         // 6
  const secApi = showApi ? ++s : s; // 7 (conditional)
  const secModels = showModels ? ++s : s; // 8 (conditional)
  const secSetup = ++s;           // 9
  const secDeploy = ++s;          // 10
  const secTheory = showThesis ? ++s : s; // 11
  const secDesign = showThesis ? ++s : s; // 12
  const secIssues = showThesis ? ++s : s; // 13
  const secFuture = showThesis ? ++s : s; // 14
  const secRefs = showThesis ? ++s : s; // 15

  // ---- Title Page ----
  lines.push(`# ${name} - Technical Thesis and Documentation`);
  lines.push(`*Generated by Prodocu from ${sourceRef}*`);
  lines.push(`*Date: ${new Date().toISOString().split("T")[0]}*`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ---- Table of Contents ----
  lines.push("## Table of Contents");
  lines.push("");
  const tocItems: string[] = [
    `${secAbstract}. Abstract`,
    `${secTech}. Technology Stack`,
    `${secArch}. Architecture`,
  ];
  if (showDiagrams) tocItems.push(`${secDiagrams}. Diagrams`);
  tocItems.push(`${secFolders}. Folder Structure`);
  tocItems.push(`${secModules}. Key Modules`);
  if (showApi) tocItems.push(`${secApi}. API Endpoints`);
  if (showModels) tocItems.push(`${secModels}. Data Models`);
  tocItems.push(`${secSetup}. Setup Instructions`);
  tocItems.push(`${secDeploy}. Deployment Notes`);
  if (showThesis) {
    tocItems.push("", "Part II: Thesis Analysis", "");
    tocItems.push(`${secTheory}. Theoretical Background`);
    tocItems.push(`${secDesign}. Design Rationale and Trade-offs`);
    tocItems.push(`${secIssues}. Known Issues and Limitations`);
    tocItems.push(`${secFuture}. Future Work and Recommendations`);
    tocItems.push(`${secRefs}. References`);
  }
  for (const item of tocItems) {
    if (item === "") {
      lines.push("");
    } else {
      lines.push(`- ${item}`);
    }
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  // ---- 1. Abstract / Overview ----
  if (showThesis && thesisAnalysis) {
    lines.push(`## ${secAbstract}. Abstract`);
    lines.push("");
    lines.push(thesisAnalysis.abstract);
    lines.push("");
  } else {
    lines.push(`## ${secAbstract}. Overview`);
    lines.push("");
    lines.push(documentation.overview);
    lines.push("");
  }

  // ---- 2. Technology Stack ----
  lines.push(`## ${secTech}. Technology Stack`);
  lines.push("");
  lines.push("| Category | Technologies |");
  lines.push("|---|---|");
  lines.push(`| **Languages** | ${techStack.languages.join(", ") || "-"} |`);
  lines.push(`| **Frameworks/Libraries** | ${techStack.frameworks.join(", ") || "-"} |`);
  lines.push(`| **Databases/Storage** | ${techStack.databases.join(", ") || "-"} |`);
  lines.push(`| **Build Tools** | ${techStack.buildTools.join(", ") || "-"} |`);
  lines.push(`| **Testing Tools** | ${techStack.testingTools.join(", ") || "-"} |`);
  lines.push(`| **Architecture Pattern** | ${techStack.architecturePattern} |`);
  lines.push("");
  lines.push(techStack.summary);
  lines.push("");

  // ---- 3. Architecture ----
  lines.push(`## ${secArch}. Architecture`);
  lines.push("");
  lines.push(documentation.architecture);
  lines.push("");

  // ---- 4. Diagrams ----
  if (showDiagrams && diagrams) {
    lines.push(`## ${secDiagrams}. Diagrams`);
    lines.push("");
    for (const d of diagrams) {
      lines.push(`### ${d.title}`);
      lines.push(`*Type: \`${d.type}\`*`);
      lines.push("");
      lines.push("```mermaid");
      lines.push(d.mermaidCode.trim());
      lines.push("```");
      lines.push("");
    }
  }

  // ---- 5. Folder Structure ----
  lines.push(`## ${secFolders}. Folder Structure`);
  lines.push("");
  lines.push(documentation.folderStructure);
  lines.push("");

  // ---- 6. Key Modules ----
  lines.push(`## ${secModules}. Key Modules`);
  lines.push("");
  for (const m of documentation.keyModules) {
    lines.push(`- **\`${m.name}\`** - ${m.description}`);
  }
  lines.push("");

  // ---- 7. API Endpoints ----
  if (showApi) {
    lines.push(`## ${secApi}. API Endpoints`);
    lines.push("");
    lines.push("| Method | Path | Description |");
    lines.push("|---|---|---|");
    for (const e of documentation.apiEndpoints) {
      lines.push(`| \`${e.method}\` | \`${e.path}\` | ${e.description} |`);
    }
    lines.push("");
  }

  // ---- 8. Data Models ----
  if (showModels) {
    lines.push(`## ${secModels}. Data Models`);
    lines.push("");
    for (const model of documentation.dataModels) {
      lines.push(`### ${model.name}`);
      lines.push("");
      lines.push(model.description);
      lines.push("");
      lines.push("| Field | Details |");
      lines.push("|---|---|");
      for (const field of model.fields) {
        lines.push(`| \`${field}\` | - |`);
      }
      lines.push("");
    }
  }

  // ---- 9. Setup Instructions ----
  lines.push(`## ${secSetup}. Setup Instructions`);
  lines.push("");
  lines.push(documentation.setupInstructions);
  lines.push("");

  // ---- 10. Deployment Notes ----
  lines.push(`## ${secDeploy}. Deployment Notes`);
  lines.push("");
  lines.push(documentation.deploymentNotes);
  lines.push("");

  // ---- Part II: Thesis Analysis ----
  if (showThesis && thesisAnalysis) {
    lines.push("---");
    lines.push("");
    lines.push("# Part II: Thesis Analysis");
    lines.push("");
    lines.push("---");
    lines.push("");

    // 11. Theoretical Background
    lines.push(`## ${secTheory}. Theoretical Background`);
    lines.push("");
    lines.push(thesisAnalysis.theoreticalBackground);
    lines.push("");

    // 12. Design Rationale
    lines.push(`## ${secDesign}. Design Rationale and Trade-offs`);
    lines.push("");
    for (const dr of thesisAnalysis.designRationale) {
      lines.push(`### ${dr.title}`);
      lines.push("");
      lines.push(dr.discussion);
      lines.push("");
    }

    // 13. Known Issues
    lines.push(`## ${secIssues}. Known Issues and Limitations`);
    lines.push("");
    for (const issue of thesisAnalysis.knownIssues) {
      lines.push(`### ${issue.title}`);
      lines.push("");
      lines.push(`**Area:** ${issue.area}  `);
      lines.push(`**Impact:** ${issue.impact}  `);
      lines.push("");
      lines.push(issue.description);
      lines.push("");
      lines.push(`**Proposed Solution:** ${issue.proposedSolution}`);
      lines.push("");
    }

    // 14. Future Work
    lines.push(`## ${secFuture}. Future Work and Recommendations`);
    lines.push("");
    for (const fw of thesisAnalysis.futureWork) {
      lines.push(`### ${fw.title} \`[${fw.priority.toUpperCase()}]\``);
      lines.push("");
      lines.push(fw.description);
      lines.push("");
    }

    // 15. References
    lines.push(`## ${secRefs}. References`);
    lines.push("");
    for (let i = 0; i < thesisAnalysis.references.length; i++) {
      const r = thesisAnalysis.references[i];
      lines.push(`[${i + 1}] ${r.authors} (${r.year}). *${r.title}*. ${r.source}.`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
