import {
  Document, Packer, Paragraph, HeadingLevel, TextRun, Table, TableRow,
  TableCell, WidthType, ImageRun, BorderStyle, AlignmentType,
} from "docx";
import type { ProjectExportData } from "../buildMarkdown";
import { renderMermaidToPng } from "../renderDiagram";

function thesisHeading(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]) {
  return new Paragraph({ text, heading: level, spacing: { before: 360, after: 200 } });
}

function thesisParagraph(text: string) {
  return new Paragraph({ children: [new TextRun(text)], spacing: { after: 200 } });
}

function thesisBullet(text: string) {
  return new Paragraph({ text, bullet: { level: 0 }, spacing: { after: 80 } });
}

function thesisTableCell(textValue: string, boldValue = false) {
  return new TableCell({
    children: [new Paragraph({
      children: [new TextRun({ text: textValue, bold: boldValue, size: 20 })],
    })],
    width: { size: 33, type: WidthType.PERCENTAGE },
  });
}

function thesisSubheading(text: string) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_3, spacing: { before: 240, after: 120 } });
}

export async function exportDocx(data: ProjectExportData): Promise<Buffer> {
  const { name, sourceRef, techStack, documentation, diagrams, thesisAnalysis } = data;
  const children: (Paragraph | Table)[] = [];

  // Title page
  children.push(
    new Paragraph({ spacing: { before: 3000 } }),
    new Paragraph({
      children: [new TextRun({
        text: name + " - Technical Thesis and Documentation",
        bold: true, size: 52, color: "2C3E50",
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: "Generated by Prodocu from " + sourceRef,
        italics: true, size: 22, color: "7F8C8D",
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: new Date().toISOString().split("T")[0],
        size: 20, color: "95A5A6",
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
  );

  // 1. Abstract / Overview
  if (thesisAnalysis) {
    children.push(thesisHeading("1. Abstract", HeadingLevel.HEADING_1));
    children.push(thesisParagraph(thesisAnalysis.abstract));
  } else {
    children.push(thesisHeading("1. Overview", HeadingLevel.HEADING_1));
  }
  children.push(thesisParagraph(documentation.overview));

  // 2. Technology Stack
  children.push(thesisHeading("2. Technology Stack", HeadingLevel.HEADING_1));
  children.push(thesisBullet("Languages: " + (techStack.languages.join(", ") || "-")));
  children.push(thesisBullet("Frameworks/Libraries: " + (techStack.frameworks.join(", ") || "-")));
  children.push(thesisBullet("Databases/Storage: " + (techStack.databases.join(", ") || "-")));
  children.push(thesisBullet("Build Tools: " + (techStack.buildTools.join(", ") || "-")));
  children.push(thesisBullet("Testing Tools: " + (techStack.testingTools.join(", ") || "-")));
  children.push(thesisBullet("Architecture Pattern: " + techStack.architecturePattern));
  children.push(thesisParagraph(techStack.summary));

  // 3. Architecture
  children.push(thesisHeading("3. Architecture", HeadingLevel.HEADING_1));
  children.push(thesisParagraph(documentation.architecture));

  // 4. Diagrams
  if (diagrams.length) {
    children.push(thesisHeading("4. Diagrams", HeadingLevel.HEADING_1));
    for (const d of diagrams) {
      children.push(thesisHeading(d.title, HeadingLevel.HEADING_2));
      try {
        const png = await renderMermaidToPng(d.mermaidCode);
        children.push(
          new Paragraph({
            children: [new ImageRun({ data: png, transformation: { width: 550, height: 330 }, type: "png" })],
            spacing: { after: 200 },
          })
        );
      } catch {
        children.push(thesisParagraph("[Diagram could not be rendered - Mermaid source below]"));
        children.push(thesisParagraph(d.mermaidCode));
      }
    }
  }

  // 5. Folder Structure
  children.push(thesisHeading("5. Folder Structure", HeadingLevel.HEADING_1));
  children.push(thesisParagraph(documentation.folderStructure));

  // 6. Key Modules
  children.push(thesisHeading("6. Key Modules", HeadingLevel.HEADING_1));
  for (const m of documentation.keyModules) {
    children.push(thesisBullet(m.name + " - " + m.description));
  }

  // 7. API Endpoints
  if (documentation.apiEndpoints.length) {
    children.push(thesisHeading("7. API Endpoints", HeadingLevel.HEADING_1));
    const rows = [
      new TableRow({ children: [thesisTableCell("Method", true), thesisTableCell("Path", true), thesisTableCell("Description", true)] }),
      ...documentation.apiEndpoints.map(
        (e) => new TableRow({ children: [thesisTableCell(e.method), thesisTableCell(e.path), thesisTableCell(e.description)] })
      ),
    ];
    children.push(new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } }));
  }

  // 8. Data Models
  if (documentation.dataModels.length) {
    children.push(thesisHeading("8. Data Models", HeadingLevel.HEADING_1));
    for (const model of documentation.dataModels) {
      children.push(thesisHeading(model.name, HeadingLevel.HEADING_2));
      children.push(thesisParagraph(model.description));
      for (const f of model.fields) children.push(thesisBullet(f));
    }
  }

  // 9. Setup Instructions
  children.push(thesisHeading("9. Setup Instructions", HeadingLevel.HEADING_1));
  children.push(thesisParagraph(documentation.setupInstructions));

  // 10. Deployment Notes
  children.push(thesisHeading("10. Deployment Notes", HeadingLevel.HEADING_1));
  children.push(thesisParagraph(documentation.deploymentNotes));

  // Part II: Thesis Analysis
  if (thesisAnalysis) {
    children.push(new Paragraph({
      spacing: { before: 600, after: 200 },
      children: [new TextRun({ text: "", size: 1 })],
      border: { top: { style: BorderStyle.DOUBLE, size: 6, color: "AAAAAA" } },
    }));
    children.push(thesisHeading("Part II: Thesis Analysis", HeadingLevel.HEADING_1));

    // 11. Theoretical Background
    children.push(thesisHeading("11. Theoretical Background", HeadingLevel.HEADING_1));
    children.push(thesisParagraph(thesisAnalysis.theoreticalBackground));

    // 12. Design Rationale
    children.push(thesisHeading("12. Design Rationale and Trade-offs", HeadingLevel.HEADING_1));
    for (const dr of thesisAnalysis.designRationale) {
      children.push(thesisSubheading(dr.title));
      children.push(thesisParagraph(dr.discussion));
    }

    // 13. Known Issues
    children.push(thesisHeading("13. Known Issues and Limitations", HeadingLevel.HEADING_1));
    for (const issue of thesisAnalysis.knownIssues) {
      children.push(thesisSubheading(issue.title));
      children.push(new Paragraph({
        spacing: { after: 100 },
        children: [
          new TextRun({ text: "Area: ", bold: true, size: 20 }),
          new TextRun({ text: issue.area, size: 20 }),
        ],
      }));
      children.push(new Paragraph({
        spacing: { after: 100 },
        children: [
          new TextRun({ text: "Impact: ", bold: true, size: 20 }),
          new TextRun({ text: issue.impact, size: 20 }),
        ],
      }));
      children.push(thesisParagraph(issue.description));
      children.push(new Paragraph({
        spacing: { after: 200 },
        children: [
          new TextRun({ text: "Proposed Solution: ", bold: true, italics: true, size: 20 }),
          new TextRun({ text: issue.proposedSolution, size: 20 }),
        ],
      }));
    }

    // 14. Future Work
    children.push(thesisHeading("14. Future Work and Recommendations", HeadingLevel.HEADING_1));
    for (const fw of thesisAnalysis.futureWork) {
      const priorityColor = fw.priority === "high" ? "E74C3C" : fw.priority === "medium" ? "F39C12" : "27AE60";
      children.push(new Paragraph({
        spacing: { before: 200 },
        children: [
          new TextRun({ text: fw.title + " ", bold: true, size: 22 }),
          new TextRun({ text: "[" + fw.priority.toUpperCase() + "]", size: 18, color: priorityColor }),
        ],
      }));
      children.push(thesisParagraph(fw.description));
    }

    // 15. References
    children.push(thesisHeading("15. References", HeadingLevel.HEADING_1));
    for (let i = 0; i < thesisAnalysis.references.length; i++) {
      const r = thesisAnalysis.references[i];
      const refParts: TextRun[] = [
        new TextRun({ text: "[" + (i + 1) + "] ", size: 20, color: "7F8C8D" }),
        new TextRun({ text: r.title + ". ", italics: true, size: 20 }),
        new TextRun({ text: r.authors, size: 20 }),
      ];
      if (r.year) {
        refParts.push(new TextRun({ text: " (" + r.year + ").", size: 20 }));
      }
      if (r.source) {
        refParts.push(new TextRun({ text: " " + r.source + ".", size: 20 }));
      }
      children.push(new Paragraph({
        spacing: { after: 120 },
        children: refParts,
      }));
    }
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
    styles: {
      default: {
        document: {
          run: { font: "Times New Roman", size: 24 },
          paragraph: { spacing: { after: 120, line: 360 } },
        },
      },
    },
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
